name: Java CI with Gradle and Docker

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt install gnome-terminal
        sudo apt-get install ./docker-desktop-amd64.deb
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo usermod -aG docker $USER

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my_project:latest .

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/my_project:latest